# -*- coding: utf-8 -*-
"""TTS Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HsfFVw-LkvRhps7iiN2FGN9okfVpc8wv
"""

!pip install transformers soundfile torch

from transformers import SpeechT5Processor, SpeechT5ForTextToSpeech, SpeechT5HifiGan
import torch
import soundfile as sf
from IPython.display import Audio

processor = SpeechT5Processor.from_pretrained("microsoft/speecht5_tts")
model = SpeechT5ForTextToSpeech.from_pretrained("microsoft/speecht5_tts")
vocoder = SpeechT5HifiGan.from_pretrained("microsoft/speecht5_hifigan")

text = "Hello Rohit, this is a simple text to speech project.how are you i hope you fine"
inputs = processor(text=text, return_tensors="pt")

# random speaker embedding (works fine for project)
speaker_embeddings = torch.zeros(1, 512)

speech = model.generate_speech(inputs["input_ids"], speaker_embeddings, vocoder=vocoder)

sf.write("speech.wav", speech.numpy(), samplerate=16000)
Audio("speech.wav")